# Generated by Django 4.2.7 on 2023-11-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0002_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
