# Generated by Django 4.2.7 on 2023-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0004_remove_record_profile_image_record_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
