# Generated by Django 4.2.7 on 2023-11-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0005_alter_record_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='image_field',
            new_name='profile_image',
        ),
    ]
