# Generated by Django 4.2.7 on 2023-11-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0006_rename_image_field_record_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='images/'),
        ),
    ]
