# Generated by Django 4.2.7 on 2023-11-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0007_alter_record_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
